"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var theme_1 = require("../../style/theme");
var StyledButton = styled_components_1.default.button(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: inline-block;\n  border-radius: 2px;\n  font-style: normal;\n  font-stretch: normal;\n  line-height: normal;\n  letter-spacing: 0.2px;\n  cursor: pointer;\n  outline: 0;\n  border: 1px solid transparent;\n\n  &:active {\n    outline: none;\n    box-shadow: none;\n    text-decoration: none;\n  }\n\n  &.hmly-button-primary {\n    background-color: ", ";\n    color: #ffffff;\n  }\n\n  &.hmly-button-sm {\n    padding: 6px 20px;\n  }\n  &.hmly-button-md {\n    padding: 10px 25px;\n  }\n  &.hmly-button-lg {\n    padding: 14px 29px;\n    font-size: 16px;\n    font-weight: bold;\n  }\n\n  &.hmly-button-primary {\n    background-color: ", ";\n    color: #ffffff;\n  }\n  &.hmly-button-yellow {\n    background-color: ", ";\n    color: #ffffff;\n  }\n  &.hmly-button-white-primary {\n    background-color: #ffffff;\n    color: #9b9b9b;\n    border: 1px solid rgba(83, 118, 130, 0.8);\n  }\n  &.hmly-button-white-cyan {\n    background-color: #ffffff;\n    color: ", ";\n    border: 1px solid ", ";\n  }\n\n  &.hmly-button-block {\n    width: 100%;\n  }\n\n  &.hmly-button-disabled {\n    background-color: #a6a6a6;\n    color: #ffffff;\n    cursor: not-allowed;\n    border: 1px solid transparent;\n  }\n"], ["\n  display: inline-block;\n  border-radius: 2px;\n  font-style: normal;\n  font-stretch: normal;\n  line-height: normal;\n  letter-spacing: 0.2px;\n  cursor: pointer;\n  outline: 0;\n  border: 1px solid transparent;\n\n  &:active {\n    outline: none;\n    box-shadow: none;\n    text-decoration: none;\n  }\n\n  &.hmly-button-primary {\n    background-color: ", ";\n    color: #ffffff;\n  }\n\n  &.hmly-button-sm {\n    padding: 6px 20px;\n  }\n  &.hmly-button-md {\n    padding: 10px 25px;\n  }\n  &.hmly-button-lg {\n    padding: 14px 29px;\n    font-size: 16px;\n    font-weight: bold;\n  }\n\n  &.hmly-button-primary {\n    background-color: ", ";\n    color: #ffffff;\n  }\n  &.hmly-button-yellow {\n    background-color: ", ";\n    color: #ffffff;\n  }\n  &.hmly-button-white-primary {\n    background-color: #ffffff;\n    color: #9b9b9b;\n    border: 1px solid rgba(83, 118, 130, 0.8);\n  }\n  &.hmly-button-white-cyan {\n    background-color: #ffffff;\n    color: ", ";\n    border: 1px solid ", ";\n  }\n\n  &.hmly-button-block {\n    width: 100%;\n  }\n\n  &.hmly-button-disabled {\n    background-color: #a6a6a6;\n    color: #ffffff;\n    cursor: not-allowed;\n    border: 1px solid transparent;\n  }\n"])), theme_1.primaryBtnColor, theme_1.primaryBtnColor, theme_1.yellowBtnColor, theme_1.primaryBtnColor, theme_1.primaryBtnColor);
exports.default = StyledButton;
var templateObject_1;
//# sourceMappingURL=StyledButton.js.map