export declare const primaryBtnColor = "#ff4444";
export declare const yellowBtnColor = "#ffba0f";
export declare const primaryCheckboxColor = "#313646";
export declare const primaryRadioColor = "#313646";
export declare const colorQuaternary: string;
export declare const colorTertiary: string;
export declare const colorSecondary: string;
export declare const colorPrimary: string;
export declare const colorPrimaryDarker: string;
export declare const colorPremium: string;
export declare const colorRedPrimary: string;
