"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var IconType;
(function (IconType) {
    IconType["close"] = "close";
    IconType["down"] = "down";
    IconType["right"] = "right";
    IconType["left"] = "left";
    IconType["up"] = "up";
    IconType["instagram"] = "instagram";
    IconType["twitter"] = "twitter";
    IconType["facebook"] = "facebook";
    IconType["locked"] = "locked";
    IconType["unlocked"] = "unlocked";
    IconType["volumeLow"] = "volume-low";
    IconType["volumeHigh"] = "volume-high";
    IconType["volumeMuted"] = "volume-muted";
    IconType["loopList"] = "loop-list";
    IconType["loopSingle"] = "loop-single";
    IconType["shuffle"] = "shuffle";
    IconType["question"] = "question";
    IconType["pause"] = "pause";
    IconType["playerNext"] = "player-next";
    IconType["play"] = "play";
    IconType["playerPrev"] = "player-prev";
    IconType["sortDown"] = "sort-down";
    IconType["playlist"] = "playlist";
    IconType["sortUp"] = "sort-up";
    IconType["share"] = "share";
    IconType["liked"] = "liked";
    IconType["like"] = "like";
    IconType["visible"] = "visible";
    IconType["invisible"] = "invisible";
    IconType["drag"] = "drag";
    IconType["dragMouse"] = "drag-mouse";
    IconType["upload"] = "upload";
    IconType["enter"] = "enter";
    IconType["edit"] = "edit";
    IconType["download"] = "download";
    IconType["stats"] = "stats";
    IconType["delete"] = "delete";
    IconType["more"] = "more";
    IconType["filter"] = "filter";
    IconType["people"] = "people";
    IconType["disc"] = "disc";
})(IconType = exports.IconType || (exports.IconType = {}));
//# sourceMappingURL=IconTypeEnum.js.map