import { InlineSubMenuProps, PopSubMenuBoxProps } from '../interface';
declare const StyledMenu: import("styled-components").StyledComponent<"ul", any, {}, never>;
declare const StyledMenuItem: import("styled-components").StyledComponent<"li", any, {}, never>;
declare const StyledSubMenu: import("styled-components").StyledComponent<"li", any, {}, never>;
declare const SubMenuTitle: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const InlineSubMenu: import("styled-components").StyledComponent<"ul", any, InlineSubMenuProps, never>;
declare const PopSubMenuBox: import("styled-components").StyledComponent<"div", any, PopSubMenuBoxProps, never>;
declare const PopSubMenu: import("styled-components").StyledComponent<"ul", any, {}, never>;
declare const BackToMenu: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const StyledAnimateHeight: import("styled-components").StyledComponent<"div", any, {}, never>;
export { StyledMenu, StyledMenuItem, StyledSubMenu, SubMenuTitle, InlineSubMenu, PopSubMenu, PopSubMenuBox, StyledAnimateHeight, BackToMenu };
