"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var animation_1 = require("../../../styles/animation");
var StyledMenu = styled_components_1.default.ul(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  list-style: none;\n  padding: 0;\n"], ["\n  list-style: none;\n  padding: 0;\n"])));
exports.StyledMenu = StyledMenu;
var StyledMenuItem = styled_components_1.default.li(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  color: #4a4a4a;\n  width: 100%;\n  height: 40px;\n  padding: 0 22px;\n  line-height: 40px;\n  font-size: 14px;\n  font-weight: 400;\n  font-style: normal;\n  font-stretch: normal;\n  letter-spacing: normal;\n  text-align: left;\n  box-sizing: border-box;\n  position: relative;\n  cursor: pointer;\n  white-space:nowrap;\n  &:hover {\n    background-color: #f3f3f3;\n    color: #4a4a4a;\n    font-weight: 600;\n  }\n  &.hmly-menu-item-checked {\n    font-weight: bold;\n    color: #3a3a3a;\n  }\n  &.hmly-menu-item-disabled {\n    color: #ccc;\n    cursor: not-allowed;\n  }\n"], ["\n  color: #4a4a4a;\n  width: 100%;\n  height: 40px;\n  padding: 0 22px;\n  line-height: 40px;\n  font-size: 14px;\n  font-weight: 400;\n  font-style: normal;\n  font-stretch: normal;\n  letter-spacing: normal;\n  text-align: left;\n  box-sizing: border-box;\n  position: relative;\n  cursor: pointer;\n  white-space:nowrap;\n  &:hover {\n    background-color: #f3f3f3;\n    color: #4a4a4a;\n    font-weight: 600;\n  }\n  &.hmly-menu-item-checked {\n    font-weight: bold;\n    color: #3a3a3a;\n  }\n  &.hmly-menu-item-disabled {\n    color: #ccc;\n    cursor: not-allowed;\n  }\n"])));
exports.StyledMenuItem = StyledMenuItem;
var StyledSubMenu = styled_components_1.default.li(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  height: auto;\n  position: relative;\n"], ["\n  height: auto;\n  position: relative;\n"])));
exports.StyledSubMenu = StyledSubMenu;
var SubMenuTitle = styled_components_1.default.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  color: #4a4a4a;\n  width: 100%;\n  height: 40px;\n  padding: 0 22px;\n  line-height: 40px;\n  font-size: 14px;\n  font-weight: 400;\n  font-style: normal;\n  font-stretch: normal;\n  letter-spacing: normal;\n  text-align: left;\n  box-sizing: border-box;\n  position: relative;\n  cursor: pointer;\n  &:hover {\n    background-color: #f3f3f3;\n    color: #4a4a4a;\n    font-weight: 600;\n  }\n  &.hmly-submenu-title-inline::after {\n    position: absolute;\n    top: calc(50% - 8px);\n    right: 25px;\n    height: 10px;\n    width: 10px;\n    content: \" \";\n    border-right: 2px solid #9B9B9B;\n    border-top: 2px solid #9B9B9B;\n    border-left: 2px solid transparent;\n    border-bottom: 2px solid transparent;\n    display: inline-block;\n    transform: rotate(135deg);\n    box-sizing: border-box;\n  }\n  &.hmly-submenu-title-pop::after,\n  &.hmly-submenu-title-replace::after {\n    position: absolute;\n    top: calc(50% - 5px);\n    right: 10px;\n    height: 10px;\n    width: 10px;\n    content: \" \";\n    border-right: 2px solid #9B9B9B;\n    border-top: 2px solid #9B9B9B;\n    border-left: 2px solid transparent;\n    border-bottom: 2px solid transparent;\n    display: inline-block;\n    transform: rotate(45deg);\n    box-sizing: border-box;\n  }\n  &.hmly-submenu-title-inline.hmly-submenu-title-expand::after {\n    transform: rotate(-45deg);\n  }\n"], ["\n  color: #4a4a4a;\n  width: 100%;\n  height: 40px;\n  padding: 0 22px;\n  line-height: 40px;\n  font-size: 14px;\n  font-weight: 400;\n  font-style: normal;\n  font-stretch: normal;\n  letter-spacing: normal;\n  text-align: left;\n  box-sizing: border-box;\n  position: relative;\n  cursor: pointer;\n  &:hover {\n    background-color: #f3f3f3;\n    color: #4a4a4a;\n    font-weight: 600;\n  }\n  &.hmly-submenu-title-inline::after {\n    position: absolute;\n    top: calc(50% - 8px);\n    right: 25px;\n    height: 10px;\n    width: 10px;\n    content: \" \";\n    border-right: 2px solid #9B9B9B;\n    border-top: 2px solid #9B9B9B;\n    border-left: 2px solid transparent;\n    border-bottom: 2px solid transparent;\n    display: inline-block;\n    transform: rotate(135deg);\n    box-sizing: border-box;\n  }\n  &.hmly-submenu-title-pop::after,\n  &.hmly-submenu-title-replace::after {\n    position: absolute;\n    top: calc(50% - 5px);\n    right: 10px;\n    height: 10px;\n    width: 10px;\n    content: \" \";\n    border-right: 2px solid #9B9B9B;\n    border-top: 2px solid #9B9B9B;\n    border-left: 2px solid transparent;\n    border-bottom: 2px solid transparent;\n    display: inline-block;\n    transform: rotate(45deg);\n    box-sizing: border-box;\n  }\n  &.hmly-submenu-title-inline.hmly-submenu-title-expand::after {\n    transform: rotate(-45deg);\n  }\n"])));
exports.SubMenuTitle = SubMenuTitle;
var InlineSubMenu = styled_components_1.default(StyledMenu)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  height: ", ";\n  overflow: hidden;\n  padding-left: 20px;\n"], ["\n  height: ", ";\n  overflow: hidden;\n  padding-left: 20px;\n"])), function (props) { return props.height; });
exports.InlineSubMenu = InlineSubMenu;
var PopSubMenuBox = styled_components_1.default.div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  position: absolute;\n  top: 0;\n  right: ", ";\n  z-index: 999;\n  width: ", ";\n  border: 1px solid #eee;\n  box-sizing: border-box;\n  transform-origin: left center;\n  animation: .15s ", " ease-in;\n"], ["\n  position: absolute;\n  top: 0;\n  right: ", ";\n  z-index: 999;\n  width: ", ";\n  border: 1px solid #eee;\n  box-sizing: border-box;\n  transform-origin: left center;\n  animation: .15s ", " ease-in;\n"])), function (props) { return props.right; }, function (props) { return props.width; }, animation_1.pageTurning);
exports.PopSubMenuBox = PopSubMenuBox;
var PopSubMenu = styled_components_1.default.ul(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  list-style: none;\n  padding: 0;\n  background-color: #fff;\n  box-sizing: border-box;\n"], ["\n  list-style: none;\n  padding: 0;\n  background-color: #fff;\n  box-sizing: border-box;\n"])));
exports.PopSubMenu = PopSubMenu;
var BackToMenu = styled_components_1.default.div(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  color: #4a4a4a;\n  width: 100%;\n  height: 40px;\n  padding: 0 22px 0 45px;\n  line-height: 40px;\n  font-size: 14px;\n  font-weight: 400;\n  font-style: normal;\n  font-stretch: normal;\n  position: relative;\n  cursor: pointer;\n  &::after {\n    position: absolute;\n    top: calc(50% - 5px);\n    left: 25px;\n    height: 10px;\n    width: 10px;\n    content: \" \";\n    border-right: 2px solid #9B9B9B;\n    border-top: 2px solid #9B9B9B;\n    border-left: 2px solid transparent;\n    border-bottom: 2px solid transparent;\n    display: inline-block;\n    transform: rotate(225deg);\n    box-sizing: border-box;\n  }\n"], ["\n  color: #4a4a4a;\n  width: 100%;\n  height: 40px;\n  padding: 0 22px 0 45px;\n  line-height: 40px;\n  font-size: 14px;\n  font-weight: 400;\n  font-style: normal;\n  font-stretch: normal;\n  position: relative;\n  cursor: pointer;\n  &::after {\n    position: absolute;\n    top: calc(50% - 5px);\n    left: 25px;\n    height: 10px;\n    width: 10px;\n    content: \" \";\n    border-right: 2px solid #9B9B9B;\n    border-top: 2px solid #9B9B9B;\n    border-left: 2px solid transparent;\n    border-bottom: 2px solid transparent;\n    display: inline-block;\n    transform: rotate(225deg);\n    box-sizing: border-box;\n  }\n"])));
exports.BackToMenu = BackToMenu;
var StyledAnimateHeight = styled_components_1.default.div(templateObject_9 || (templateObject_9 = __makeTemplateObject([""], [""])));
exports.StyledAnimateHeight = StyledAnimateHeight;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9;
//# sourceMappingURL=index.js.map