import { IdomProps } from '../Input';
import { IWrapperProps } from '../Wrapper';
declare const StyledInput: import("styled-components").StyledComponent<"input", any, IdomProps, never>;
declare const StyledIcon: import("styled-components").StyledComponent<"span", any, IWrapperProps, never>;
declare const StyledWrapper: import("styled-components").StyledComponent<"div", any, IWrapperProps, never>;
declare const StyledWrapperBorder: import("styled-components").StyledComponent<"span", any, IWrapperProps, never>;
declare const StyledWrapperPlaceholder: import("styled-components").StyledComponent<"span", any, IWrapperProps, never>;
declare const StyledWrapperMsg: import("styled-components").StyledComponent<"span", any, IWrapperProps, never>;
declare const StyledTextArea: import("styled-components").StyledComponent<"textarea", any, IWrapperProps, never>;
export { StyledInput, StyledIcon, StyledWrapper, StyledWrapperBorder, StyledWrapperPlaceholder, StyledWrapperMsg, StyledTextArea };
