import { LabelBoxProps } from '../interface';
import Icon from '../../Icon';
declare const StyledForm: import("styled-components").StyledComponent<"form", any, {}, never>;
declare const StyledFormItem: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const LabelBox: import("styled-components").StyledComponent<"div", any, LabelBoxProps, never>;
declare const ControlBox: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const FormItemLabel: import("styled-components").StyledComponent<"label", any, {}, never>;
declare const FormItemDesc: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const FormItemControl: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const ItemError: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const LabelIcon: import("styled-components").StyledComponent<typeof Icon, any, {}, never>;
export { StyledForm, StyledFormItem, FormItemLabel, FormItemControl, FormItemDesc, LabelBox, ControlBox, ItemError, LabelIcon };
