"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var theme_1 = require("../../../styles/theme");
var StyledCheckboxBox = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: relative;\n  padding: 0;\n  list-style: none;\n  display: inline-block;\n  line-height: 1.5;\n  white-space: nowrap;\n  cursor: pointer;\n  box-sizing: border-box;\n  margin-top: -2px;\n  color: #767676;\n  font-weight: 600;\n  & + & {\n    margin-left: 40px;\n  }\n"], ["\n  position: relative;\n  padding: 0;\n  list-style: none;\n  display: inline-block;\n  line-height: 1.5;\n  white-space: nowrap;\n  cursor: pointer;\n  box-sizing: border-box;\n  margin-top: -2px;\n  color: #767676;\n  font-weight: 600;\n  & + & {\n    margin-left: 40px;\n  }\n"])));
exports.StyledCheckboxBox = StyledCheckboxBox;
var StyledCheckbox = styled_components_1.default.span(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: relative;\n  display: inline-block;\n  margin: 0;\n  padding: 0;\n  list-style: none;\n  outline: none;\n  white-space: nowrap;\n  cursor: pointer;\n  line-height: 1;\n  vertical-align: text-top;\n"], ["\n  position: relative;\n  display: inline-block;\n  margin: 0;\n  padding: 0;\n  list-style: none;\n  outline: none;\n  white-space: nowrap;\n  cursor: pointer;\n  line-height: 1;\n  vertical-align: text-top;\n"])));
exports.StyledCheckbox = StyledCheckbox;
var CheckboxInner = styled_components_1.default.span(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  position: relative;\n  top: 0;\n  left: 0;\n  display: block;\n  width: 16px;\n  height: 16px;\n  border-radius: 2px;\n  transition: all 0.1s;\n  box-sizing: border-box;\n  background-color: #f5f5f5;\n  border-color: ", ";\n  border-width: 1px;\n  border-style: solid;\n  &::after {\n    position: absolute;\n    transform: rotate(45deg) scale(1);\n    border-color: ", ";\n    border-width: 2px;\n    border-style: solid;\n    border-top: 0;\n    border-left: 0;\n    left: 5px;\n    top: 1px;\n    display: table;\n    width: 5px;\n    height: 9px;\n    content: \" \";\n    transition: all 0.1s cubic-bezier(.78,.14,.15,.86);\n    box-sizing: border-box;\n  }\n"], ["\n  position: relative;\n  top: 0;\n  left: 0;\n  display: block;\n  width: 16px;\n  height: 16px;\n  border-radius: 2px;\n  transition: all 0.1s;\n  box-sizing: border-box;\n  background-color: #f5f5f5;\n  border-color: ", ";\n  border-width: 1px;\n  border-style: solid;\n  &::after {\n    position: absolute;\n    transform: rotate(45deg) scale(1);\n    border-color: ", ";\n    border-width: 2px;\n    border-style: solid;\n    border-top: 0;\n    border-left: 0;\n    left: 5px;\n    top: 1px;\n    display: table;\n    width: 5px;\n    height: 9px;\n    content: \" \";\n    transition: all 0.1s cubic-bezier(.78,.14,.15,.86);\n    box-sizing: border-box;\n  }\n"])), function (props) { return props.disabled ? '#979797' : theme_1.primaryCheckboxColor; }, function (props) { return props.checked ? (props.disabled ? 'rgba(0,0,0,.25)' : '#313646') : '#f5f5f5'; });
exports.CheckboxInner = CheckboxInner;
var CheckboxInput = styled_components_1.default.input(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  position: absolute;\n  left: 0;\n  top: 0;\n  bottom: 0;\n  right: 0;\n  z-index: 1;\n  opacity: 0;\n  padding: 0;\n  width: 50px;\n  height: 20px;\n  box-sizing: border-box;\n  color: ", ";\n  cursor: ", ";\n"], ["\n  position: absolute;\n  left: 0;\n  top: 0;\n  bottom: 0;\n  right: 0;\n  z-index: 1;\n  opacity: 0;\n  padding: 0;\n  width: 50px;\n  height: 20px;\n  box-sizing: border-box;\n  color: ", ";\n  cursor: ", ";\n"])), function (props) { return props.disabled ? 'rgba(0,0,0,.25)' : ''; }, function (props) { return props.disabled ? 'not-allowed' : 'pointer'; });
exports.CheckboxInput = CheckboxInput;
var CheckboxSlot = styled_components_1.default.span(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  display: inline-block;\n  word-wrap: break-word;\n  white-space: pre-wrap;\n  margin-top: -2px;\n  padding-left: 13px;\n  font-size: 14px;\n  line-height: 24px;\n  cursor: pointer;\n  box-sizing: border-box;\n  vertical-align: text-top;\n  color: ", ";\n  cursor: ", ";\n"], ["\n  display: inline-block;\n  word-wrap: break-word;\n  white-space: pre-wrap;\n  margin-top: -2px;\n  padding-left: 13px;\n  font-size: 14px;\n  line-height: 24px;\n  cursor: pointer;\n  box-sizing: border-box;\n  vertical-align: text-top;\n  color: ", ";\n  cursor: ", ";\n"])), function (props) { return props.disabled ? 'rgba(0,0,0,.25)' : ''; }, function (props) { return props.disabled ? 'not-allowed' : 'pointer'; });
exports.CheckboxSlot = CheckboxSlot;
var StyledCheckboxGroup = styled_components_1.default.div(templateObject_6 || (templateObject_6 = __makeTemplateObject([""], [""])));
exports.StyledCheckboxGroup = StyledCheckboxGroup;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
//# sourceMappingURL=index.js.map