import { EmptyInnerProps, StyledTableHeaderProps, StyledFilterProps } from '../interface';
import Icon from '../../Icon';
declare const StyledTableBox: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const StyledTableHeader: import("styled-components").StyledComponent<"thead", any, StyledTableHeaderProps, never>;
declare const StyledTr: import("styled-components").StyledComponent<"tr", any, {}, never>;
declare const StyledTd: import("styled-components").StyledComponent<"td", any, {}, never>;
declare const StyledTdInner: import("styled-components").StyledComponent<"div", any, {}, never>;
declare const StyledTh: import("styled-components").StyledComponent<"th", any, {}, never>;
declare const EmptyInner: import("styled-components").StyledComponent<"span", any, EmptyInnerProps, never>;
declare const EmptyImage: import("styled-components").StyledComponent<"img", any, {}, never>;
declare const StyledFilter: import("styled-components").StyledComponent<typeof Icon, any, StyledFilterProps, never>;
declare const StyledPaginationBox: import("styled-components").StyledComponent<"div", any, {}, never>;
export { StyledTableBox, StyledTableHeader, StyledTr, StyledTd, StyledTh, EmptyInner, EmptyImage, StyledFilter, StyledPaginationBox, StyledTdInner };
